Running software as another user

diff --git a/0x12-web_stack_debugging_2/0-iamsomeoneelse b/0x12-web_stack_debugging_2/0-iamsomeoneelse
--- a/0x12-web_stack_debugging_2/0-iamsomeoneelse
+++ b/0x12-web_stack_debugging_2/0-iamsomeoneelse
@@ -1,8 +1,13 @@
 #!/usr/bin/env bash
 # command that gives a user superuser privileges
 
-if [ -n "$1" ]; then
-   su -c "whoami" "$1"
+if [ -z "$1" ]; then
+   whoami
 else
-   su -s /bin/bash -c "whoami" "$1"
+   if id "$1" &>/dev/null; then
+      su -s /bin/bash -c "whoami" "$1"
+   else
+      echo "Error: User '$1' does not exist on the system."
+      exit 1
+   fi
 fi
